# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/challenge
spring.datasource.username=userDB
spring.datasource.password=passDB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MinIO Configuration
minio.url=http://localhost:9000
minio.access-key=a4PNp7uLJz5pbM5FaegH
minio.secret-key=Nr3RvZ4GVe7uMlWQgeLCOO1JicTT9cyukGvTPDoG
minio.bucket-name=document-bucket